test:
  name: abc

spring: 
  jooq: 
    sql-dialect: postgres

datasource: 
  enabled: true

datasourceprop: 
  props: 
    default: 
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://db:5432/GGTRXDB
      username: compose-postgres
      password: compose-postgres
      
WORKFLOW_URL: http://workflow-service/api/execute-workflow
WORKFLOW_SLEEPTIME: 1000      
